# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAbout(object):
    def setupUi(self, DialogAbout):
        DialogAbout.setObjectName("DialogAbout")
        DialogAbout.setWindowModality(QtCore.Qt.WindowModal)
        DialogAbout.resize(240, 332)
        DialogAbout.setSizeGripEnabled(False)
        DialogAbout.setModal(True)
        self.splitter = QtWidgets.QSplitter(DialogAbout)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 241, 331))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.labelImage = QtWidgets.QLabel(self.splitter)
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap(":/images/images/logo.jpeg"))
        self.labelImage.setScaledContents(True)
        self.labelImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage.setObjectName("labelImage")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.labelCopyright = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.labelCopyright.setFont(font)
        self.labelCopyright.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCopyright.setObjectName("labelCopyright")
        self.gridLayout.addWidget(self.labelCopyright, 2, 0, 1, 1)
        self.labelApplicationName = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.labelApplicationName.setFont(font)
        self.labelApplicationName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelApplicationName.setObjectName("labelApplicationName")
        self.gridLayout.addWidget(self.labelApplicationName, 0, 0, 1, 1)
        self.labelApplicationVersion = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.labelApplicationVersion.setFont(font)
        self.labelApplicationVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelApplicationVersion.setObjectName("labelApplicationVersion")
        self.gridLayout.addWidget(self.labelApplicationVersion, 1, 0, 1, 1)
        self.labelCredits = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.labelCredits.setFont(font)
        self.labelCredits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCredits.setObjectName("labelCredits")
        self.gridLayout.addWidget(self.labelCredits, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(DialogAbout)
        self.buttonBox.accepted.connect(DialogAbout.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogAbout.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAbout)

    def retranslateUi(self, DialogAbout):
        _translate = QtCore.QCoreApplication.translate
        DialogAbout.setWindowTitle(_translate("DialogAbout", "About GetExtIP"))
        self.labelCopyright.setText(_translate("DialogAbout", "©2021-2022 Advanced Design and Manufacturing, LLC"))
        self.labelApplicationName.setText(_translate("DialogAbout", "GetExtIP"))
        self.labelApplicationVersion.setText(_translate("DialogAbout", "Version 1.0.5"))
        self.labelCredits.setText(_translate("DialogAbout", "Credits: DDSchrader"))
import resources_rc
